server:
  port: ${AGENT_PORT}
  address: 0.0.0.0
  tomcat:
    max-http-form-post-size: -1
    max-swallow-size: -1

agent:
  ip-address: ${AGENT_IP:auto}
  nexus:
    url: ${AGENT_NEXUS_URL}
  name: ${AGENT_NAME}
  upload:
    directory: ./data/uploads
  heartbeat:
    interval: 30000
  ui:
    username: ${AGENT_UI_USERNAME}
    password: ${AGENT_UI_PASSWORD}
    jwt-secret: ${AGENT_JWT_SECRET}

logging:
  file:
    name: ./logs/agent.log

spring:
  application:
    name: beamlink-agent
  servlet:
    multipart:
      enabled: ${MULTIPART_ENABLED}
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
      file-size-threshold: ${MULTIPART_FILE_SIZE_THRESHOLD}
  web:
    resources:
      static-locations: file:./static/,classpath:/static/
