server:
  port: ${NEXUS_PORT:7472}
  address: 0.0.0.0

spring:
  application:
    name: beamlink-nexus
  servlet:
    multipart:
      enabled: ${MULTIPART_ENABLED:true}
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
      file-size-threshold: ${MULTIPART_FILE_SIZE_THRESHOLD}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

nexus:
  data:
    directory: ./data
  update:
    storage-path: ./update-package
  approval:
    required: true
  name: ${NEXUS_NAME}
  monitoring:
    interval: 60000
  upload:
    directory: ./received_files
  jwt:
    secret: ${NEXUS_JWT_SECRET}
  cors:
    static-origins: http://localhost:5173
  admin:
    username: ${NEXUS_ADMIN_USERNAME}
    password: ${NEXUS_ADMIN_PASSWORD}
  ip-address: ${NEXUS_IP}

logging:
  level:
    root: INFO
    com.atamanahmet.beamlink: INFO
  file:
    name: nexus.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
