server:
  port: ${NEXUS_PORT:7472}
  address: 0.0.0.0

spring:
  application:
    name: beamlink-nexus
  servlet:
    multipart:
      enabled: ${MULTIPART_ENABLED:true}
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
      file-size-threshold: ${MULTIPART_FILE_SIZE_THRESHOLD}
  datasource:
    url: jdbc:h2:file:./data/database/${DB_NAME};MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=${DB_PORT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

nexus:
  data:
    directory: ./data
  update:
    storage-path: ./update-package
  approval:
    required: true
  name: ${NEXUS_NAME}
  monitoring:
    interval: 60000
  upload:
    directory: ./received_files
  jwt:
    secret: ${NEXUS_JWT_SECRET}
    admin-expiration-minutes: ${NEXUS_JWT_ADMIN_EXPIRATION_MINUTES}
    agent-auth-expiration-days: ${NEXUS_JWT_AGENT_AUTH_EXPIRATION_DAYS}
    agent-public-expiration-days: ${NEXUS_JWT_AGENT_PUBLIC_EXPIRATION_DAYS}
  cors:
    static-origins: http://localhost:5173
  admin:
    username: ${NEXUS_ADMIN_USERNAME}
    password: ${NEXUS_ADMIN_PASSWORD}
  ip-address: ${NEXUS_IP}

logging:
  level:
    root: INFO
    com.atamanahmet.beamlink: INFO
  file:
    name: logs/nexus.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
